### ISSUE TITLE
CVE2017-12615tomcat远程代码执行漏洞readonly为True

### ISSUE THREAD

**Issue by noshowtime** [Medicean/VulApps#14]
使用了CVE2017-12615tomcat远程代码执行漏洞，测试不成功，进入容器发现readonly的值为true。

**Comment by Medicean** [comment]
不应该啊，我刚测试了一下是成功的，具体看一下这里：

https://github.com/Medicean/VulApps/blob/master/t/tomcat/1/src/web.xml#L116
