### ISSUE TITLE
蚁逅Docker搭建成功，无法登录，账号密码不正确

### ISSUE THREAD

**Issue by AI0TSec** [Medicean/VulApps#27]
![image](https://user-images.githubusercontent.com/48520137/60229204-b428d700-98c7-11e9-8a18-05444b396f6e.png)
管理员账号密码   是  i@root.cool   123456 吧？怎么登不上去嘞？
那我注册一下？
![image](https://user-images.githubusercontent.com/48520137/60229345-200b3f80-98c8-11e9-9396-439d48803159.png)
结果也注册不了欸。。。

**Comment by Medicean** [comment]
这情况多半是 mongodb 数据没导进去

用这里最新的

https://github.com/AntSwordProject/ant
