### ISSUE TITLE
有几个容器中科大镜像没有

### ISSUE THREAD

**Issue by tuola** [Medicean/VulApps#4]
medicean/vulapps:r_redis_1 这个中科大没有
medicean/vulapps:n_nagios_1
medicean/vulapps:o_openssl_heartbleed 这两个用中科大特别慢 

解决办法：registry-mirror=https://2h3po24q.mirror.aliyuncs.com  特别快

**Comment by Medicean** [comment]
Mirrors 一般是只读的，会定期删除缓存以节省服务器空间，出现这种情况多试几次或者换Mirrors就可以了。感谢建议。
