### ISSUE TITLE
wordpress 5 REST API 4.7.0 4.7.1 Content Injection 漏洞环境中的wordpress 会自动升级到4.7.2

### ISSUE THREAD

**Issue by AlkenePan** [Medicean/VulApps#5]
![image](https://cloud.githubusercontent.com/assets/8273781/22616367/b76b6f72-eae6-11e6-83df-633b433c0d56.png)

**Comment by Medicean** [comment]
@AlkenePan 已经更正，重新拉取镜像或者直接在 wp-config.php 文件中添加

```
define('WP_AUTO_UPDATE_CORE', false);
define('AUTOMATIC_UPDATER_DISABLED', true);
```

https://github.com/Medicean/VulApps/commit/d3871dd7c6b6c1b572db488503780812602ea3e8#diff-a294e05cd4c20a76c80e044868e966deR25

**Comment by AlkenePan** [comment]
@Medicean cool
